/// Flutter icons NexusIcons
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NexusIcons
///      fonts:
///       - asset: fonts/NexusIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NexusIcons {
  NexusIcons._();

  static const _kFontFam = 'NexusIcons';
  static const String? _kFontPkg = null;

  static const IconData send_arrow_forward_outlined = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_ok = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_at = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData square_tiles = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stars = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_mode = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upgoing_arrow = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vertical_dots = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData web = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_contact = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_image = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blocked = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_specific = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_outlined = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_outlined = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chats = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_running = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData earth = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_outlined = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horizontal_dots = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_marker = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_content = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_dot = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nexus_logo = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password_reset = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circle = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_outlined = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_arrow_forward = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
